### ISSUE TITLE
setSwipeTabBarEnabled(enabled: Bool) conflicts with UIGesture

### ISSUE THREAD

**Issue by HackShitUp** [marcosgriselli/SwipeableTabBarController#19] opened 2017-07-25 23:58 UTC
Is it possible to traverse this protocol for a UIView instead of a UIViewController?
I have a UITableViewCell with a horizontal scrolling UICollectionView in it and it seems to conflict with the UIPangesture (I'm assuming) so it swipes between the UITabBarController's view controllers instead of scrolling through the UICollectionView in the UITableViewCell.

**Comment by marcosgriselli** [comment] 2017-07-26 18:23
@HackShitUp do you have a sample project I can check out? I might have a solution to test on this particular case but I don't have the time to build a demo example.

**Comment by SummerHF** [comment] 2017-07-27 04:13
if add a tableview or collectionView,the gesture can not work,can you solve it?

**Comment by marcosgriselli** [comment] 2017-08-06 16:23
@HackShitUp any update?

**Comment by HackShitUp** [comment] 2017-08-06 20:43
@marcosgriselli Sorry for the late response, I've been busy starting up. I'll try to share a sample project as soon as I can, and post the Git URL here.

**Comment by HackShitUp** [comment] 2017-08-06 21:25
@marcosgriselli https://github.com/HackShitUp/SwipeIssue

**Comment by marcosgriselli** [comment] 2017-08-07 11:55
I checked it out and this quick fix will be good until I come back home in a couple days. 

On your `extension TableViewController: UICollectionViewDataSource, UICollectionViewDelegate` add 

```
    override func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
        setTabBarSwipe(enabled: false)
    }
    
    override func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        setTabBarSwipe(enabled: true)
    }
``` 

This will disable the SwipeableTabBarController interaction when using a `UIScrollView` and reactivate it when you finish using it. 

I'll come up with a solution integrated to the library next week.

**Comment by HackShitUp** [comment] 2017-08-07 20:03
@marcosgriselli Perfect, I completely forgot about the scroll view delegate methods. Thank you!

**Comment by moazkh60** [comment] 2017-10-12 07:27
@marcosgriselli I tried your solution and it sometimes work and sometimes doesn't. After a certain time the app gets stuck and the views start overlapping.

**Comment by HackShitUp** [comment] 2017-10-12 07:31
@moazkh60 Are you customizing the tabBar?

**Comment by moazkh60** [comment] 2017-10-12 07:43
No but I have two collection view in my screen, one is horizontal and one is vertical, so I need to disable the swipe when my horizontal collection view is being scrolled. When I do this using the above mentioned methods of scrollView it works the first time and as soon as I lift the finger up and try again it's stuck. If I try to move to some other tab and come back the screen starts to overlap.

**Comment by marcosgriselli** [comment] 2017-10-12 14:08
@moazkh60 Can you expand on the 'it's stuck' part? Do you mind building a simple demo project?

**Comment by moazkh60** [comment] 2017-10-13 04:31
Stuck like I can't scroll the collection view anymore or click on any item in the collection view but I am able to click other tabs at the tab bar and move to some other screen when I return back the swipe able controller starts to overlap the screens and now the screen that got stuck is just plain white because the view of that screen is now overlapped to some other screen. Ok I will try to replicate the issue in a sample project and let you know.

**Comment by moazkh60** [comment] 2017-10-13 06:22
@marcosgriselli I have replicated the issue. Please check my replicated issue project on GitHub using this link
[SwipeableTabBarController screen overLap issue replicated](https://github.com/moazkh60/SwipeableTabBarController-ReplicatedIssue)

**Comment by marcosgriselli** [comment] 2017-10-13 12:39
Thanks @moazkh60. I'll be checking this tonight.

**Comment by moazkh60** [comment] 2017-10-13 12:46
Thanks. I will be waiting for your response.

**Comment by moazkh60** [comment] 2017-10-15 13:33
@marcosgriselli did you check?

**Comment by marcosgriselli** [comment] 2017-10-15 14:25
@moazkh60 I was just checking it, the app crashes when trying to move to the second viewController on the SwipeableTabBar, there's something wrong with the Storyboard outlets. Can you fix them and push?

**Comment by moazkh60** [comment] 2017-10-15 15:09
@marcosgriselli I just cloned the repo and tried again the app is crashing on second screen because you forgot to install the pods. Please install the pods using pod Install and open the project using xcworkspace not xcproj

Thanks.

**Comment by marcosgriselli** [comment] 2017-10-15 15:20
You are referencing a viewController called `SecondTabVC` that doesn't exist from `Main.storyboard`. Maybe you forgot to add it to the project. 

Crash: 
<img width="723" alt="screen shot 2017-10-15 at 12 15 45 pm" src="https://user-images.githubusercontent.com/14804033/31586089-b76753c8-b1a2-11e7-978a-4db7b3d982a8.png">

Main storyboard reference:
<img width="261" alt="screen shot 2017-10-15 at 12 15 58 pm" src="https://user-images.githubusercontent.com/14804033/31586090-b8b34fc0-b1a2-11e7-82b2-5e70767b08e5.png">

Project files:
<img width="274" alt="screen shot 2017-10-15 at 12 17 54 pm" src="https://user-images.githubusercontent.com/14804033/31586111-edf454b8-b1a2-11e7-84c7-b9145a09f507.png">

**Comment by moazkh60** [comment] 2017-10-15 15:40
I think you didn't download properly. Here is the link https://github.com/moazkh60/SwipeableTabBarController-ReplicatedIssue/blob/master/SwipeableTabBarController-ReplicatedIssue/SecondTabVC.swift

**Comment by marcosgriselli** [comment] 2017-10-15 17:02
Got it, not sure why it wasn't appearing on the project. 
Ok so found a solution 🎉. Check it out: 

![img_2356 trim-3](https://user-images.githubusercontent.com/14804033/31587075-4f550bd6-b1b1-11e7-999e-7cb2e4f909b0.gif)


I'll be updating the library during the next weekend when I have some extra time to work out a generic solution so I don't introduce any 'hacky fixes'. 

Just as an exception you could edit the pod's `SwipeInteractor's` `UIGestureRecognizerDelegate` to look like this: 

```swift 
// MARK: - UIGestureRecognizerDelegate
extension SwipeInteractor: UIGestureRecognizerDelegate {

    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if let collectionView = otherGestureRecognizer.view as? UICollectionView {
            if let flowLayout = collectionView.collectionViewLayout as? UICollectionViewFlowLayout {
                if flowLayout.scrollDirection == .horizontal {
                    return false
                }
            }
        }
        if gestureRecognizer == panRecognizer {
            if let point = panRecognizer?.translation(in: panRecognizer?.view?.superview) {
                return fabs(point.x) < InteractionConstants.xTranslationForRecognition
            }
        }
        return true
    }
}
```

**Comment by deafjam** [comment] 2017-10-15 17:17
Marcos, it's issue for my problem to?

**Comment by moazkh60** [comment] 2017-10-16 05:05
The issue is resolved to some extent but it's still there. I think when I swipe fast then the screen starts to overlap. Try installing the issue app on mobile and do some stress testing moving horizontal scrolling on second screen and then moving between all the tabs using swipe gesture a bit fast. You will see the issue.

**Comment by marcosgriselli** [comment] 2017-10-16 15:22
@moazkh60 You are right. This will need deeper revision as it's a complicated issue. It's triggered by `UIPercentDrivenTransition` calling a start transition method again before finishing the previous one. I'll go over it in the weekend.

**Comment by moazkh60** [comment] 2017-10-17 04:29
Thanks @marcosgriselli I will be waiting.

**Comment by moazkh60** [comment] 2017-10-23 07:59
@marcosgriselli any updates?

**Comment by moazkh60** [comment] 2017-11-05 11:51
@marcosgriselli did you resolve the issue yet ? Let me know if it gets resolved soon otherwise I would have no other option but to remove the library from my project.

**Comment by marcosgriselli** [comment] 2017-11-06 02:57
Hi @moazkh60, I've been super busy with work and another library I released. I haven't had the time to look into this yet. I plan to fix this but I don't have an approximate milestone date. I'll keep the issue open to keep you or anyone else interested posted.

**Comment by moazkh60** [comment] 2017-12-04 08:53
@marcosgriselli I am still waiting for your update I am dependent on your library now. I know you might be busy but please try to find some time to resolve this issue. I would really appreciate it. Thanks for the effort and thanks for the awesome library.

**Comment by umarhussain15** [comment] 2017-12-15 12:52
When will you resolve this issue. I'm stuck in my development of app due to this issue. I have to disable several features. Kindly provide the fix. @marcosgriselli

**Comment by marcosgriselli** [comment] 2017-12-15 13:10
@moazkh60 @umarhussain15 sorry for the delay. I've been super busy. Just released version `1.0.10` which fixes this issue 🎉. No more black screens. 

The debugger will still show the _unbalanced calls to begin/end_ message but it won't mess up with the usability. I plan to fix those soon.

**Comment by moazkh60** [comment] 2017-12-18 10:31
@marcosgriselli thanks for the update finally 👍. Now the issue is resolved to some extent. Whenever I run the app the first time and try to swipe immediately same issue of white screen occurs. But on the second run it works fine. Kindly look into that thanks.

**Comment by marcosgriselli** [comment] 2017-12-18 21:35
@moazkh60 second run meaning you close the app and run it again? I have an idea to solve this. Are you convining version `1.0.10` and the code for supporting horizontal `UICollectionView's` from above?

**Comment by moazkh60** [comment] 2017-12-19 05:41
@marcosgriselli  yes I close the app and run it again. No I am on a different page when my app starts, so horizontal UICollectionView is not above. Few points to be noted

1. It happens if I run the app and immediately start to swipe. The screen get stuck and then suddenly the white screen appears just like before but this time all screens are white.
2. If I click on the bottom tabs first and move through all the tabs. After that I start swiping the problem doesn't appear.
3. I think that it's taking a bit of time to adjust with the layout that's why if I click on tabs and then swipe it works fine. I am not sure.

**Comment by moazkh60** [comment] 2017-12-26 06:12
@marcosgriselli any further updates?

**Comment by marcosgriselli** [comment] 2018-02-27 00:20
I'm closing this issue as it drifted away from the original issue. I have more time to delicate to open source projects now so issues will be tackled a lot faster. @moazkh60 if you're still using this library feel free to create any new issue with a good description and we'll solve it :)

**Closed as completed by marcosgriselli** 2018-02-27 00:20 UTC
Labels: question
